language: node_js
node_js:
 - "node"
cache: yarn
install:
  - yarn install
before_script:
  - npm install -g typescript jest-cli truffle tslint ethereumjs-testrpc
  - testrpc &
script:
  - yarn tslint
  - yarn test-ci
  - yarn truffle-test