language: node_js
node_js:
 - "node"
cache: yarn
install:
  - yarn install
before_script:
  - npm install -g jest-cli
  - npm install -g typescript
  - npm install -g truffle
  - npm install -g tslint
  - npm install -g ganache-cli
  - testrpc &
script:
  - yarn tslint
  - yarn test-ci
  - yarn truffle-test